---
output: 
html_document:
code_folding: hide
pagetitle: Assignments
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<style>
div.gray { background-color:#5594A0; border-radius: 5px; padding: 20px;}
</style>
<div class = "gray">


<style>
div.blue { background-color:#61A4B7; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
## [HOME](http://KellyTroconis.github.io/) | [ABOUT ME](http://KellyTroconis.github.io/About-me/) | [DATA COURSE](http://KellyTroconis.github.io/data-course/) | [PROJECT](http://KellyTroconis.github.io/PROJECT/)
</div>
___
## **Data Analysis UVU**

#### This page contains assignments from the data entry class, made with R Markdown. The over all goal is to obtain the basic skills to clean and analyzed data with R. 

#### This website is still a work in progress. I am looking forward to keep developing my data analysis skills. This website will be use to keep my progress updated.  

##### Here is the link to my personal GitHub, which contains class notes and other assignments. (https://github.com/KellyTroconis/Data_Course_COOK) 

<br>
</div>
___
<style>
div.green { background-color:#9CD3A9; border-radius: 5px; padding: 20px;}
</style>
<div class = "green">
#### **Assignment 9** [Grad schools Admissions](http://KellyTroconis.github.io/data-course/Assignment_9.html)

**In this assignment, you will use R (within R-Studio) to:**

  - Load and clean a real data set.  
  - Conduct exploratory analyses, including informative figures.
  - Build and test appropriate models.
  - Draw conclusions about your data.
  - Combine all of the above into a well-documented R-Markdown report and export (knit) it into an HTML file.
</div>

___
<style>
div.gray { background-color:#5594A0; border-radius: 5px; padding: 20px;}
</style>
<div class = "gray">

#### **Exam 3** [Exam 3](http://KellyTroconis.github.io/data-course/Exam_3.html)

**Model Building and Testing**

  - Workflow 
  - R-mtcar.

<br>

</div>

___

